# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'SportsPreferences' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for SportsPreferences
   pod 'Firebase/Core'
   pod 'Firebase/Firestore'
   pod 'Firebase/Auth'



  target 'SportsPreferencesTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'SportsPreferencesUITests' do
    # Pods for testing
  end

end
